# .markdownlint.yaml
# Markdown linting configuration for HAMLET project

# Line length: Allow longer lines for technical documentation
MD013:
  line_length: 140
  code_blocks: false  # Don't check code blocks
  tables: false       # Don't check tables
  headings: false     # Don't check headings

# Allow inline HTML (needed for custom formatting, badges, etc.)
MD033: false

# Allow emphasis as heading (common in notes/callouts like **NOTE:**)
# Keep enabled to encourage proper heading structure
MD036: true

# Allow multiple top-level headings (common in large docs with sections)
MD025: false

# Allow bare URLs in certain contexts (will be auto-linked by renderers)
MD034: false

# First line heading: Not always needed (front matter, templates, agent files)
MD041: false

# Allow duplicate headings (common in structured docs with repeated sections)
MD024:
  siblings_only: true  # Only flag duplicates at the same level

# Ordered list style: Prefer ordered numbering
MD029:
  style: ordered

# Unordered list style: Prefer dash (-)
MD004:
  style: dash

# Code block style: Prefer fenced code blocks
MD046:
  style: fenced

# Heading style: Prefer ATX style (###)
MD003:
  style: atx

# Emphasis style: Prefer ** for bold, * for italic
MD049:
  style: asterisk

MD050:
  style: asterisk

# Horizontal rule style: Prefer --- (three dashes)
MD035:
  style: "---"

# Allow trailing punctuation in headings (common for questions, emphasis)
MD026: false
