# affordances.yaml - Affordance Definitions & Effects
# This defines how agents interact with the environment and what effects those interactions have.
#
# PURPOSE: Replace 200+ line elif blocks with data-driven affordance system
# STATUS: TEMPLATE (ACTION #12 will implement AffordanceEngine to process this)
#
# Structure:
# - Each affordance defines its interaction type (instant, multi_tick, continuous)
# - Effects can be immediate or distributed over ticks
# - Costs are subtracted before effects are applied
# - Teaching notes explain game design intent

version: "1.0"
description: "Affordance definitions for Hamlet Level 1.5 (15 affordances)"
status: "TEMPLATE - Awaiting ACTION #12 implementation"

affordances:
  # ============================================================================
  # ENERGY RESTORATION
  # ============================================================================
  
  - id: "Bed"
    name: "Bed"
    category: "energy_restoration"
    interaction_type: "multi_tick"
    required_ticks: 5
    
    costs_per_tick:
      - { meter: "money", amount: 0.01 }  # $1 per tick
    
    effects_per_tick:
      - { meter: "energy", amount: 0.075, type: "linear" }  # 75% distributed over ticks
    
    completion_bonus:
      - { meter: "energy", amount: 0.125 }  # 25% bonus for completing
      - { meter: "health", amount: 0.02 }
    
    operating_hours: [0, 24]  # 24/7 available
    
    teaching_note: "Multi-tick interaction teaches commitment - must stay to get completion bonus"
    design_intent: "Primary energy restoration, requires time investment"

  - id: "LuxuryBed"
    name: "Luxury Bed"
    category: "energy_restoration"
    interaction_type: "multi_tick"
    required_ticks: 3  # Faster than regular bed
    
    costs_per_tick:
      - { meter: "money", amount: 0.05 }  # $5 per tick (expensive!)
    
    effects_per_tick:
      - { meter: "energy", amount: 0.10 }  # 100% over 3 ticks (33% per tick)
    
    completion_bonus:
      - { meter: "health", amount: 0.05 }
      - { meter: "mood", amount: 0.03 }  # Luxury feels good!
    
    operating_hours: [0, 24]
    
    teaching_note: "Money can buy time - luxury version is faster but expensive"
    design_intent: "Advanced option when agent has money but needs speed"

  # ============================================================================
  # HYGIENE RESTORATION
  # ============================================================================
  
  - id: "Shower"
    name: "Shower"
    category: "hygiene"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.01 }  # $1
    
    effects:
      - { meter: "hygiene", amount: 0.50 }  # 50% restoration
    
    operating_hours: [0, 24]
    
    teaching_note: "Instant effect - no commitment required"
    design_intent: "Tertiary meter maintenance, prevents cascade penalties"

  # ============================================================================
  # SATIATION (FOOD)
  # ============================================================================
  
  - id: "HomeMeal"
    name: "Home Meal"
    category: "food"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.15 }  # $15
    
    effects:
      - { meter: "satiation", amount: 0.60 }  # 60% restoration
      - { meter: "health", amount: 0.03 }  # Healthy bonus
    
    operating_hours: [0, 24]
    
    teaching_note: "Fundamental need - satiation affects BOTH pivotal meters"
    design_intent: "Primary food source, balanced cost/benefit"

  - id: "FastFood"
    name: "Fast Food"
    category: "food"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.10 }  # $10 (cheaper)
    
    effects:
      - { meter: "satiation", amount: 0.45 }  # Less restoration
      - { meter: "fitness", amount: -0.03 }  # Unhealthy!
      - { meter: "health", amount: -0.02 }
    
    operating_hours: [0, 24]
    
    teaching_note: "Cheap but unhealthy - demonstrates trade-offs and cascading effects"
    design_intent: "Tempting short-term option with long-term consequences"

  # ============================================================================
  # HEALTH RESTORATION
  # ============================================================================
  
  - id: "Doctor"
    name: "Doctor"
    category: "health"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.30 }  # $30
    
    effects:
      - { meter: "health", amount: 0.25 }  # 25% restoration
    
    operating_hours: [8, 18]  # Business hours only
    
    teaching_note: "Tier 1 health restoration - cheaper but limited hours"
    design_intent: "Affordable healthcare option with scheduling constraint"

  - id: "Hospital"
    name: "Hospital"
    category: "health"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.60 }  # $60 (expensive!)
    
    effects:
      - { meter: "health", amount: 0.40 }  # 40% restoration (stronger)
    
    operating_hours: [0, 24]  # 24/7 emergency care
    
    teaching_note: "Tier 2 health restoration - expensive but always available"
    design_intent: "Emergency option when money is available"

  # ============================================================================
  # MOOD RESTORATION
  # ============================================================================
  
  - id: "Therapist"
    name: "Therapist"
    category: "mood"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.50 }  # $50
    
    effects:
      - { meter: "mood", amount: 0.40 }  # 40% restoration
    
    operating_hours: [8, 18]  # Business hours
    
    teaching_note: "Tier 2 mood restoration - expensive specialist"
    design_intent: "Advanced option for mood management"

  - id: "Recreation"
    name: "Recreation"
    category: "mood"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.20 }  # $20
    
    effects:
      - { meter: "mood", amount: 0.25 }
      - { meter: "social", amount: 0.15 }
    
    operating_hours: [8, 22]  # 8am-10pm
    
    teaching_note: "Multi-benefit affordance - mood AND social"
    design_intent: "Efficient dual-purpose option"

  # ============================================================================
  # SOCIAL + MOOD COMBINATION
  # ============================================================================
  
  - id: "Bar"
    name: "Bar"
    category: "social"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.25 }  # $25
    
    effects:
      - { meter: "social", amount: 0.50 }  # BEST social restoration!
      - { meter: "mood", amount: 0.25 }
      - { meter: "health", amount: -0.05 }  # Alcohol penalty
    
    operating_hours: [18, 28]  # 6pm-4am (wraps midnight!)
    
    teaching_note: "Night-time social hub - high social gain but health cost"
    design_intent: "Demonstrates time-of-day mechanics and trade-offs"

  - id: "CoffeeShop"
    name: "Coffee Shop"
    category: "social"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.05 }  # $5 (cheap!)
    
    effects:
      - { meter: "energy", amount: 0.10 }  # Caffeine boost
      - { meter: "mood", amount: 0.10 }
      - { meter: "social", amount: 0.15 }
    
    operating_hours: [6, 18]  # 6am-6pm
    
    teaching_note: "Triple benefit, cheap, but effects are modest"
    design_intent: "Efficient morning routine option"

  # ============================================================================
  # INCOME GENERATION (JOBS)
  # ============================================================================
  
  - id: "Job"
    name: "Office Job"
    category: "income"
    interaction_type: "multi_tick"
    required_ticks: 3
    
    costs_per_tick:
      - { meter: "energy", amount: 0.05 }  # Work is tiring
    
    effects_per_tick:
      - { meter: "money", amount: 0.075 }  # $7.50 per tick
    
    completion_bonus:
      - { meter: "money", amount: 0.075 }  # $7.50 bonus = $30 total for 3 ticks
    
    operating_hours: [8, 18]  # Business hours
    
    teaching_note: "Primary income source - must work to afford other affordances"
    design_intent: "Creates economic pressure and strategic planning"

  - id: "Labor"
    name: "Manual Labor"
    category: "income"
    interaction_type: "multi_tick"
    required_ticks: 3
    
    costs_per_tick:
      - { meter: "energy", amount: 0.067 }  # More tiring than office job
    
    effects_per_tick:
      - { meter: "money", amount: 0.10 }  # $10 per tick (better pay!)
      - { meter: "fitness", amount: -0.017 }  # Physical toll
      - { meter: "health", amount: -0.017 }
    
    completion_bonus:
      - { meter: "money", amount: 0.10 }  # $10 bonus = $40 total
    
    operating_hours: [8, 18]
    
    teaching_note: "Higher pay but physical costs - demonstrates specialization"
    design_intent: "Risk/reward alternative to office job"

  # ============================================================================
  # FITNESS BUILDING
  # ============================================================================
  
  - id: "Gym"
    name: "Gym"
    category: "fitness"
    interaction_type: "instant"
    
    costs:
      - { meter: "money", amount: 0.15 }  # $15
      - { meter: "energy", amount: 0.10 }  # Working out is tiring
    
    effects:
      - { meter: "fitness", amount: 0.20 }  # 20% fitness gain
    
    operating_hours: [0, 24]
    
    teaching_note: "Costs both money AND energy but builds fitness (prevents health cascade)"
    design_intent: "Proactive health maintenance, prevents death spiral"

  - id: "Park"
    name: "Park"
    category: "fitness"
    interaction_type: "instant"
    
    costs: []  # FREE!
    
    effects:
      - { meter: "fitness", amount: 0.20 }
      - { meter: "social", amount: 0.15 }
      - { meter: "mood", amount: 0.15 }
    
    operating_hours: [6, 22]  # 6am-10pm
    
    teaching_note: "Free multi-benefit affordance - teaches optimal resource management"
    design_intent: "Reward for discovering no-cost options"

# ============================================================================
# TEACHING NOTES & GAME DESIGN INSIGHTS
# ============================================================================

teaching_insights:
  fundamental_loop: "Money (Jobs) → Satiation (Food) → Energy (Bed) → Work again"
  
  cascade_prevention: "Tertiary meters (Hygiene, Social) must be maintained to prevent cascades to Secondary (Satiation, Fitness, Mood) and ultimately Pivotal (Health, Energy)"
  
  time_constraints: "Operating hours force scheduling decisions - can't do everything at once"
  
  economic_pressure: "Money is the gate - must work to afford most recovery affordances"
  
  specialization: "Multiple paths to same goal (Doctor vs Hospital, Job vs Labor) teach trade-offs"
  
  free_options: "Park is free but limited hours - teaches optimal timing"
  
  multi_tick_commitment: "Bed and Jobs require commitment - can't interrupt without losing benefits"
  
  interesting_failures: "FastFood seems efficient but creates fitness/health problems later (cascade effect)"

# ============================================================================
# IMPLEMENTATION NOTES (for ACTION #12)
# ============================================================================

implementation_notes:
  schema_validation: "Use Pydantic to validate all affordance configs at load time"
  
  equivalence_testing: "Must produce identical results to current elif blocks in vectorized_env.py"
  
  engine_architecture: "AffordanceEngine should handle instant, multi_tick, and continuous interaction types"
  
  time_of_day: "Operating hours use 24-hour clock, with wraparound support for midnight (e.g., Bar 18-28 means 6pm-4am)"
  
  cost_application: "Costs are checked before interaction, subtracted per tick for multi_tick"
  
  completion_bonus: "Only awarded if agent completes all required_ticks without interruption"
  
  teaching_examples: "Create affordances_creative.yaml with unusual affordances for experimentation"
