# Quick progression config for testing adversarial curriculum
# Lower thresholds and fewer steps for fast advancement

experiment:
  name: curriculum_quick_test
  description: Fast curriculum progression for testing

curriculum:
  type: adversarial
  max_steps_per_episode: 300
  survival_advance_threshold: 0.5  # Lower than default (0.7)
  survival_retreat_threshold: 0.2   # Lower than default (0.3)
  entropy_gate: 0.6                 # Higher than default (0.5) - easier to pass
  min_steps_at_stage: 50            # Much lower than default (1000)
  device: cpu

population:
  num_agents: 5
  state_dim: 70
  action_dim: 5
  grid_size: 8

exploration:
  type: epsilon_greedy
  initial_epsilon: 1.0
  min_epsilon: 0.1
  decay_rate: 0.995

training:
  num_episodes: 100
  device: cpu
