# Level 2.1: POMDP - Integration Test
#
# Lite version for automated testing (200 episodes, ~8 minutes)
#
# See docs/TRAINING_LEVELS.md for full Level 2 specification.
# This config validates that LSTM + POMDP training works end-to-end.

# Environment configuration
environment:
  grid_size: 8
  partial_observability: true  # LEVEL 2: Agent sees 5×5 window
  vision_range: 2

# Population configuration
population:
  num_agents: 1
  learning_rate: 0.0001  # Lower LR for recurrent networks
  gamma: 0.99
  replay_buffer_capacity: 2000  # Reduced for lite version
  network_type: recurrent  # RecurrentSpatialQNetwork with LSTM

# Curriculum configuration
curriculum:
  max_steps_per_episode: 200  # Reduced from 500
  survival_advance_threshold: 0.7
  survival_retreat_threshold: 0.3
  entropy_gate: 0.5
  min_steps_at_stage: 50  # Reduced from 1000

# Exploration configuration
exploration:
  embed_dim: 128
  initial_intrinsic_weight: 0.1  # Lower for stability
  variance_threshold: 100.0
  survival_window: 50  # Reduced from 100
  epsilon_start: 1.0
  epsilon_min: 0.1  # Higher min for faster convergence
  epsilon_decay: 0.99

# Training configuration
training:
  device: cuda
  max_episodes: 200  # Integration test: ~8 minutes
