# Level 3.1: Temporal Mechanics - Integration Test
#
# Lite version for automated testing (200 episodes, ~8 minutes)
#
# See docs/TRAINING_LEVELS.md for full Level 3 specification.
# This config validates that temporal mechanics work end-to-end.

# Environment configuration
environment:
  grid_size: 8
  partial_observability: true
  vision_range: 2
  enable_temporal_mechanics: true  # NEW: Time-of-day cycles

# Population configuration
population:
  num_agents: 1
  learning_rate: 0.0001
  gamma: 0.99
  replay_buffer_capacity: 2000  # Reduced for lite version
  network_type: recurrent  # LSTM for POMDP + temporal

# Curriculum configuration
curriculum:
  max_steps_per_episode: 200  # Reduced from 500
  survival_advance_threshold: 0.7
  survival_retreat_threshold: 0.3
  entropy_gate: 0.5
  min_steps_at_stage: 50  # Reduced from 1000

# Exploration configuration
exploration:
  embed_dim: 128
  initial_intrinsic_weight: 1.0
  variance_threshold: 100.0
  survival_window: 50  # Reduced from 100
  epsilon_start: 1.0
  epsilon_min: 0.1
  epsilon_decay: 0.99

# Training configuration
training:
  device: cuda
  max_episodes: 200  # Integration test: ~8 minutes
