# Level 3: Temporal Mechanics
#
# See docs/TRAINING_LEVELS.md for complete specification.
#
# Key features (adds to Level 2):
# - 24-tick day/night cycle with operating hours
# - Multi-tick interactions (progressive benefits + completion bonuses)
# - Time-based action masking (affordances have business hours)
# - Temporal planning and opportunity cost learning
# - LSTM learns time-dependent strategies

# Environment configuration
environment:
  grid_size: 8
  partial_observability: true
  vision_range: 2

  # NEW: Temporal mechanics
  enable_temporal_mechanics: true

# Population configuration
population:
  num_agents: 1
  learning_rate: 0.0001  # Lower for recurrent + temporal complexity
  gamma: 0.99
  replay_buffer_capacity: 10000
  network_type: recurrent  # LSTM for POMDP + temporal memory

# Curriculum configuration
curriculum:
  max_steps_per_episode: 500
  survival_advance_threshold: 0.7
  survival_retreat_threshold: 0.3
  entropy_gate: 0.5
  min_steps_at_stage: 1000

# Exploration configuration
exploration:
  embed_dim: 128
  initial_intrinsic_weight: 1.0
  variance_threshold: 100.0
  survival_window: 100
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.999

# Training configuration
training:
  device: cuda
  max_episodes: 10000  # Total episodes for this training run
