# Quick test config - 10 episodes to verify everything works
experiment:
  name: quick_test
  description: "Quick test run"
  tracking_uri: "mlruns"

environment:
  grid_width: 8
  grid_height: 8
  initial_energy: 100.0
  initial_hygiene: 100.0
  initial_satiation: 100.0
  initial_money: 50.0
  energy_depletion: 0.5
  hygiene_depletion: 0.3
  satiation_depletion: 0.4
  affordance_positions:
    Bed: [1, 1]
    Shower: [6, 1]
    HomeMeal: [1, 6]
    FastFood: [5, 6]
    Job: [6, 6]
    Gym: [7, 3]
    Bar: [7, 0]
    Recreation: [0, 7]

agents:
  - agent_id: agent_0
    algorithm: dqn
    state_dim: 72
    action_dim: 5
    learning_rate: 0.001
    gamma: 0.99
    epsilon: 1.0
    epsilon_min: 0.01
    epsilon_decay: 0.995
    device: auto

training:
  num_episodes: 10  # Just 10 episodes for quick test
  max_steps_per_episode: 50
  batch_size: 32
  learning_starts: 50  # Start learning quickly
  target_update_frequency: 5
  replay_buffer_size: 1000
  save_frequency: 5
  checkpoint_dir: "test_checkpoints/"
  log_frequency: 1
  render_mode: null

metrics:
  tensorboard: false  # Disable for speed
  database: true
  database_path: "test_metrics.db"
  replay_storage: false
  live_broadcast: false
