# configs/townlet_level_2_5_temporal.yaml
# Townlet Level 2.5: Temporal Mechanics + Multi-Interaction Affordances
#
# Adds time-based mechanics on top of Level 2 POMDP:
# - 24-tick day/night cycle with operating hours
# - Multi-interaction affordances (75% linear, 25% completion bonus)
# - Agent learns temporal planning and opportunity cost

# Environment configuration
environment:
  grid_size: 8
  partial_observability: true
  vision_range: 2

  # NEW: Temporal mechanics
  enable_temporal_mechanics: true

# Population configuration
population:
  num_agents: 1
  learning_rate: 0.0001  # Lower for recurrent + temporal complexity
  gamma: 0.99
  replay_buffer_capacity: 10000
  network_type: recurrent  # LSTM for POMDP + temporal memory

# Curriculum configuration
curriculum:
  max_steps_per_episode: 500
  survival_advance_threshold: 0.7
  survival_retreat_threshold: 0.3
  entropy_gate: 0.5
  min_steps_at_stage: 1000

# Exploration configuration
exploration:
  embed_dim: 128
  initial_intrinsic_weight: 1.0
  variance_threshold: 100.0
  survival_window: 100
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.999

# Training configuration
training:
  device: cuda
